#!/bin/bash
#
#	/etc/rc.d/init.d/nagios-api
#
# Starts the Nagios API
# (RedHat/CentOS only!)
#
# chkconfig: 2345 90 10
# description: Nagios API Daemon

# processname: nagios-api

source /etc/rc.d/init.d/functions

PROG="nagios-api"
DESC="Nagios API Daemon"
RETVAL=0
LOGFILE="/var/log/nagios/nagios-api.log"

NAG_API_BIN=/usr/bin/nagios-api
NAG_API_BINDADDR="localhost"
NAG_API_PORT=8080
NAG_API_PID=/var/run/$PROG.pid

NAGIOS_STATUS_FILE=/var/log/nagios/status.dat
NAGIOS_COMMAND_FILE=/var/log/nagios/rw/nagios.cmd
NAGIOS_LOG_FILE=/var/log/nagios/nagios.log

start() {
  # Start nagios-api only if nagios is running
  if [ -n "`pidofproc nagios`" ]; then
    echo -n "Starting $DESC ($PROG): "
    daemon $NAG_API_BIN -b $NAG_API_BINDADDR -p $NAG_API_PORT -s $NAGIOS_STATUS_FILE -c $NAGIOS_COMMAND_FILE -l $NAGIOS_LOG_FILE > $LOGFILE 2>&1 &
    RETVAL=$?
  else
    echo -n "Nagios must be started first"
    echo_failure
    RETVAL=7
  fi

  echo
  return $RETVAL
}

stop() {
  echo -n "Shutting down $DESC ($PROG): "
  killproc $PROG

  echo
  RETVAL=$?
  return $RETVAL
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  status)
	status -p ${NAG_API_PID} ${NAG_API_BIN}
	RETVAL=$?
	;;
  restart)
	stop
	start
	RETVAL=$?
	;;
  *)
	echo $"Usage: $0 {start|stop|status|restart}"
	RETVAL=1
esac

exit $RETVAL
